# Site settings
author: Sam stoltenberg
title: My Dev Canvas
header-img: img/ram.jpg
image: img/site-img.png
email: sam@skelouse.com
copyright_name: Sam stoltenberg
description: A Humble Abode For My Biased Blogs About Things I Have Learned In Python, Data Science, And Programming in General
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  skelouse

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
